standard_error 18.447914389486588
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    afaf
NameError: name 'afaf' is not defined
